"use client";
import { useState, type FormEvent } from "react";
import { Button, Field, Input, Select, Textarea } from "@/src/components/ui";
import type { CategoryResponse } from "@/src/lib/api/types";

const COVER_LIMIT=5*1024*1024, PDF_LIMIT=25*1024*1024;
type SubmitState={kind:"error"|"forbidden";message:string}|null;

export function SubmissionForm({categories}:{categories:CategoryResponse[]}){
  const [status,setStatus]=useState<SubmitState>(null);const [pending,setPending]=useState(false);
  async function submit(event:FormEvent<HTMLFormElement>){
    event.preventDefault();setStatus(null);const form=new FormData(event.currentTarget);const cover=form.get("cover_image"),document=form.get("document");
    if(cover instanceof File&&cover.size&&(cover.size>COVER_LIMIT||!cover.type.startsWith("image/"))){setStatus({kind:"error",message:"Frontend safety policy: the cover must be an image no larger than 5 MB."});return;}
    if(document instanceof File&&document.size&&(document.size>PDF_LIMIT||document.type!=="application/pdf")){setStatus({kind:"error",message:"Frontend safety policy: the document must be a PDF no larger than 25 MB."});return;}
    setPending(true);
    try{const response=await fetch("/api/research",{method:"POST",body:form});const body=await response.json().catch(()=>({}));if(response.status===401){window.location.assign(`/login?next=${encodeURIComponent("/student/research/new")}`);return;}if(response.status===403){setStatus({kind:"forbidden",message:"Your authenticated account is not permitted to submit research. The backend allows student and admin roles only."});return;}if(!response.ok){setStatus({kind:"error",message:body.error?.message??"The research submission could not be created."});return;}window.location.assign(`/research/${body.id}`);}catch{setStatus({kind:"error",message:"The submission service is unavailable. Your entered text remains in the form; choose the files again if the browser clears them."});}finally{setPending(false);}
  }
  return <form className="panel submission-form" onSubmit={submit} aria-describedby="submission-limit-note"><p className="eyebrow">[ Exact multipart contract ]</p><h2 className="section-title">Research information</h2><Field label="Thai title" required><Input name="title_th" required disabled={pending}/></Field><Field label="English title" required><Input name="title_en" className="latin" required disabled={pending}/></Field><Field label="Category" required><Select name="category_id" required defaultValue="" disabled={pending}><option value="" disabled>Select a category</option>{categories.map(x=><option key={x.id} value={x.id}>{x.category_name}</option>)}</Select></Field><Field label="Abstract"><Textarea name="abstract" disabled={pending}/></Field><div className="form-grid"><Field label="Department"><Input name="department" disabled={pending}/></Field><Field label="Work type"><Input name="work_type" disabled={pending}/></Field><Field label="Academic year"><Input name="academic_year" type="number" min="1900" max="2200" disabled={pending}/></Field><Field label="Keywords"><Input name="keywords" placeholder="Comma-separated keywords" disabled={pending}/></Field></div><Field label="Cover image" hint="Frontend safety policy: image, maximum 5 MB."><Input name="cover_image" type="file" accept="image/*" disabled={pending}/></Field><Field label="PDF document" hint="Frontend safety policy: PDF, maximum 25 MB."><Input name="document" type="file" accept="application/pdf" disabled={pending}/></Field><div id="submission-limit-note" className="state compact-state"><p>Author and advisor lookup is not available. The proxy sends <code>author_ids=[]</code> and <code>advisor_ids=[]</code>. Drafts, editing, revisions, and resubmission are not offered.</p></div>{status&&<div className={`status-message ${status.kind}`} role="alert">{status.message}</div>}<Button type="submit" disabled={pending}>{pending?"Submitting…":"Submit research"}</Button></form>;
}
