"use client";
import { useState, type FormEvent } from "react";
import Link from "next/link";
import { Button, Checkbox, Field, Input } from "@/src/components/ui";

interface ClientError { message:string; issues?:Array<{loc:Array<string|number>;msg:string}>; }
async function postJson(path:string,value:unknown){ const response=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(value)}); const body=await response.json(); if(!response.ok) throw body.error as ClientError; return body; }

export function LoginForm(){ const [error,setError]=useState(""); const [pending,setPending]=useState(false); async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setPending(true);setError("");const data=new FormData(event.currentTarget);try{await postJson("/api/auth/login",{email:data.get("email"),password:data.get("password")});window.location.assign("/dashboard/student");}catch(value){setError((value as ClientError)?.message??"ไม่สามารถเข้าสู่ระบบได้");setPending(false);}} return <form className="form-card" style={{display:"grid",gap:22,marginTop:30}} onSubmit={submit}><div className="eyebrow" style={{textAlign:"center"}}>เข้าสู่ระบบด้วยอีเมล</div><Field label="อีเมลสถาบัน" required><Input type="email" name="email" placeholder="name@university.ac.th" autoComplete="email" required/></Field><Field label="รหัสผ่าน" required><Input type="password" name="password" placeholder="กรอกรหัสผ่านของคุณ" autoComplete="current-password" required/></Field><Checkbox name="remember">จดจำการเข้าสู่ระบบบนอุปกรณ์นี้</Checkbox>{error&&<p className="status error" role="alert">{error}</p>}<Button type="submit" disabled={pending}>{pending?"กำลังเข้าสู่ระบบ…":"เข้าสู่ระบบ　→"}</Button><p style={{textAlign:"center",margin:0}}>ยังไม่มีบัญชี? <Link href="/register" style={{color:"var(--mulberry)",fontWeight:600}}>สร้างบัญชีใหม่</Link></p></form>; }

export function RegisterForm(){ const [error,setError]=useState(""); const [pending,setPending]=useState(false); async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setPending(true);setError("");const data=new FormData(event.currentTarget);if(data.get("password")!==data.get("confirmPassword")){setError("รหัสผ่านทั้งสองช่องไม่ตรงกัน");setPending(false);return;}try{await postJson("/api/auth/register",{email:data.get("email"),password:data.get("password"),first_name:data.get("first_name"),last_name:data.get("last_name")});window.location.assign("/login?registered=1");}catch(value){setError((value as ClientError)?.message??"ไม่สามารถสร้างบัญชีได้");setPending(false);}} return <form className="form-card" style={{display:"grid",gap:18,marginTop:26}} onSubmit={submit}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}><Field label="ชื่อ" required><Input name="first_name" autoComplete="given-name" required/></Field><Field label="นามสกุล" required><Input name="last_name" autoComplete="family-name" required/></Field></div><Field label="อีเมลสถาบัน" required><Input type="email" name="email" placeholder="student@university.ac.th" autoComplete="email" required/></Field><Field label="รหัสผ่าน" required hint="อย่างน้อย 8 ตัวอักษร"><Input type="password" name="password" minLength={8} autoComplete="new-password" required/></Field><Field label="ยืนยันรหัสผ่าน" required><Input type="password" name="confirmPassword" minLength={8} autoComplete="new-password" required/></Field><Checkbox required>ฉันยอมรับข้อกำหนดการใช้งานและนโยบายความเป็นส่วนตัว</Checkbox>{error&&<p className="status error" role="alert">{error}</p>}<Button type="submit" disabled={pending}>{pending?"กำลังสร้างบัญชี…":"สร้างบัญชี　→"}</Button><p style={{textAlign:"center",margin:0}}>มีบัญชีอยู่แล้ว? <Link href="/login" style={{color:"var(--mulberry)",fontWeight:600}}>เข้าสู่ระบบ</Link></p></form>; }
