import { Download, Eye, FileText } from "lucide-react";
import { notFound } from "next/navigation";
import { adminResearchSamples } from "@/src/features/admin/admin-data";
import { AdminReviewDecision } from "@/src/features/admin/admin-review-decision";

export default async function AdminReviewWorkspace({ params }: { params: Promise<{ id: string }> }) {
  const id = Number((await params).id);
  if (!Number.isInteger(id) || id < 1) notFound();
  const item = adminResearchSamples.find((record) => record.id === id) ?? adminResearchSamples[0];
  return <main className="admin-main admin-review-workspace"><header className="admin-review-document-heading"><div><p><span>{item.category}</span><code>ID: {item.ref}</code><strong>↻ รุ่น 1.2</strong></p><h1>{item.title}</h1><h2>{item.titleEn}</h2></div><dl><div><dt>วันที่ส่งผลงาน</dt><dd>[ 12 ต.ค. 2567 ]</dd></div><div><dt>วันครบกำหนด</dt><dd className="due">[ 26 ต.ค. 2567 ]</dd></div></dl></header><div className="admin-review-layout"><div className="admin-review-content"><section className="admin-abstract"><h3>บทคัดย่อ (Abstract)</h3><p>{item.abstract}</p><p>ผลการศึกษาพบว่า ความถี่และรูปแบบการบริโภคข่าวสารผ่านแพลตฟอร์มออนไลน์มีความสัมพันธ์เชิงบวกอย่างมีนัยสำคัญกับการมีส่วนร่วมทั้งในโลกออนไลน์และออฟไลน์ และสะท้อนความสำคัญของการรับฟังความคิดเห็นต่างขั้ว</p></section><section className="admin-team"><header><h3>ทีมวิจัย</h3><span>[ สมาชิก 3 คน ]</span></header><div>{[["SK", "ดร. สมศักดิ์", "ผู้วิจัยหลัก"], ["PJ", "ผศ. พิมพ์", "ผู้วิจัยร่วม"], ["NW", "นิรันดร์ ว.", "ผู้ช่วยวิจัย"]].map(([initial, name, role]) => <article key={initial}><span>{initial}</span><div><strong>{name}</strong><small>{role}</small></div></article>)}</div></section><section className="admin-manuscript"><header><div><h3>ไฟล์ต้นฉบับ</h3><p>{item.ref}_FullPaper_v1.2.pdf <span>/ 4.2 MB</span></p></div><div><button type="button"><Eye size={16} />ดูตัวอย่าง</button><button type="button"><Download size={16} />ดาวน์โหลด</button></div></header><div className="admin-document-preview"><FileText size={42} /><i /><i /><i /><span>คลิกเพื่อขยายหน้าจอแสดงผล</span></div></section></div><aside className="admin-review-sidebar"><AdminReviewDecision /><section className="admin-review-history"><h3>ประวัติการตรวจสอบ</h3><article><i /><strong>ส่งรุ่น 1.2 แล้ว</strong><small>12 ต.ค. 2567, 14:30</small><p>แก้ไขตามข้อเสนอแนะและเรียบร้อยแล้ว เพิ่มเติมส่วนการวิเคราะห์ข้อมูลเชิงคุณภาพ</p></article><article><i /><strong>ขอให้แก้ไขผลงาน</strong><small>05 ต.ค. 2567, 09:15</small><blockquote>“รบกวนขยายความในส่วนของวิธีการคัดเลือกกลุ่มตัวอย่าง”</blockquote></article><article><i /><strong>ส่งผลงานครั้งแรก</strong><small>01 ต.ค. 2567, 11:00</small></article></section></aside></div></main>;
}
