import { Download } from "lucide-react";
import { adminResearchSamples } from "@/src/features/admin/admin-data";
import { getStats } from "@/src/features/research/api";

export default async function AdminAnalyticsPage() {
  const result = await getStats();
  const stats = result.ok ? result.data : { total_users: 0, total_research_works: 0, total_views: 0, total_downloads: 0 };
  const metrics = [["Total Submissions", stats.total_research_works, "12%"], ["Active Researchers", stats.total_users, "5%"], ["Total Views", stats.total_views, "24%"], ["Downloads", stats.total_downloads, "2%"]] as const;
  return <main className="admin-main"><header className="admin-analytics-heading"><div><p>▥ Analytics Dashboard</p><h1>สถิติและการวิเคราะห์</h1><span>Insight into research submission trends, category distribution, and engagement metrics across the archive.</span></div><div className="admin-range-control"><button className="active">30 Days</button><button>Quarter</button><button>Year</button><button>Custom Range</button><button aria-label="ดาวน์โหลดรายงาน"><Download size={18} /></button></div></header><section className="admin-analytics-metrics">{metrics.map(([label, value, change], index) => <article key={label}><span>{label}</span><strong>{value.toLocaleString()}</strong><small className={index === 3 ? "down" : ""}>{index === 3 ? "↓" : "↑"}{change}</small><i><b style={{ width: `${[70, 55, 82, 66][index]}%` }} /></i></article>)}</section><div className="admin-analytics-grid"><section className="admin-chart-card admin-trend-chart"><header><h2>แนวโน้มการส่งผลงาน</h2><small>Submission trends over the selected period</small></header><div className="admin-line-chart"><svg viewBox="0 0 600 260" role="img" aria-label="กราฟแนวโน้มการส่งผลงาน"><path className="grid" d="M0 50H600M0 125H600M0 200H600"/><path className="previous" d="M0 205 C80 180 120 135 180 170 S270 230 330 105 S430 80 470 190 S540 220 600 100"/><path className="current" d="M0 180 C80 150 120 70 180 95 S260 190 320 65 S400 20 460 160 S550 170 600 55"/></svg><div><span>Jan</span><span>Feb</span><span>Mar</span><span>Apr</span><span>May</span><span>Jun</span></div></div></section><section className="admin-chart-card"><h2>ผลงานตามหมวดหมู่</h2><small>Distribution across domains</small><div className="admin-category-bars">{[84, 68, 42, 25].map((height, index) => <div key={index}><i style={{ height: `${height}%` }} /><span>{["SocSci", "Tech", "Med", "Arts"][index]}</span></div>)}</div></section><section className="admin-chart-card admin-ranking"><header><h2>อันดับการเข้าชมและการดาวน์โหลด</h2><small>Top performing research items by engagement</small></header>{adminResearchSamples.map((item, index) => <div className="admin-ranking-row" key={item.id}><span>{index + 1}</span><div><strong>{item.title}</strong><small>[ {item.ref} ]</small></div><span className="admin-category-tag">{item.category}</span><code>{item.views.toLocaleString()}</code><code>{item.downloads.toLocaleString()}</code></div>)}</section><section className="admin-chart-card admin-popular-searches"><h2>คำค้นหายอดนิยม</h2><small>Frequently searched keywords</small>{[["ปัญญาประดิษฐ์", "4.2k", 90], ["ความยั่งยืน", "3.1k", 72], ["Machine Learning", "2.8k", 60], ["นวัตกรรม", "2.1k", 47], ["เศรษฐกิจดิจิทัล", "1.5k", 35]].map(([label, value, width], index) => <div key={String(label)}><span>0{index + 1}</span><strong>{label}</strong><i><b style={{ width: `${width}%` }} /></i><code>{value}</code></div>)}</section></div></main>;
}
