grafana:
  enabled: true
  service:
    type: NodePort
    nodePort: 30300
  sidecar:
    dashboards:
      env:
        PORT: 8081
    datasources:
      env:
        PORT: 8082
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 200m
        memory: 512Mi
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
